config/routes.rb
Rails.application.routes.draw do
  devise_for :users
 
 # get 'dashboards/index'
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  devise_scope :user do
    root to: 'devise/sessions#new'
  end

  get '/dashboard', to: 'dashboards#index'

  # Employee route
  get '/employee', to: 'employees#index'
  post '/employee', to: 'employees#create'
  delete '/employee', to: 'employees#destroy'
  get '/employee/:id/edit', to: 'employees#edit'
  patch '/employees/:id', to: 'employees#update', as: 'update_employee'

  # Criteria route
  get '/criteria', to: 'criteria#index'
  post '/criteria', to: 'criteria#create'
  delete '/criteria', to: 'criteria#destroy'
  get '/criteria/:id/edit', to: 'criteria#edit'
  patch '/criteria/:id', to: 'criteria#update', as: 'update_criteria'

  #Preference Value Route
  get '/preference', to: 'preference_value#index'
  post '/preference', to: 'preference_value#create'
  delete '/preference', to: 'preference_value#destroy'
  get '/preference/:id/edit', to: 'preference_value#edit'
  patch '/preference/:id', to: 'preference_value#update', as: 'update_preference'

  #create ranking
  get '/ranking', to: 'generate_ranking#index'
  post '/ranking', to: 'generate_ranking#create'
  get '/generate_rank/:id', to: 'generate_ranking#generate_rank'
  get '/ranking_data', to: 'generate_ranking#rank_all_data'
  get '/ranking/normalisasi', to: 'generate_ranking#normalisasi'
  get '/ranking/data/normalisasi', to: 'generate_ranking#normalisasiData'
  get '/ranking/data/bobot', to: 'generate_ranking#normalisasiBobot'
  get '/ranking/data/akhir', to: 'generate_ranking#hasilAkhir'
  get '/ranking/get_json', to: 'generate_ranking#get_json'
  
  get '/log/data_source', to: 'generate_ranking#log_data_source'
  get '/log/normalisasi', to: 'generate_ranking#log_normalisasi'
  get '/log/normalisasi_bobot', to: 'generate_ranking#log_normalisasi_bobot'
  get '/log/hasil_akhir', to: 'generate_ranking#log_hasil_akhir'
  
  # create report
  get 'generate_report/employee_report', to: 'generate_report#employee_report', as: 'generate_report_employee_report'

  get 'generate_report/hasil_report', to: 'generate_report#hasil_report'
  get 'generate_report/normalisasi_bobot', to: 'generate_report#normalisasi_bobot'
  get 'generate_report/normalisasi_report', to: 'generate_report#normalisasi_report'
  


end

app/controllers/criteria_controller.rb
class CriteriaController < ApplicationController
    def index
        @kriteria = CriteriaValue.order(:id)    
        
    end

    def create
        latest_criteria = CriteriaValue.maximum(:kriteria)
        number = latest_criteria ? latest_criteria[1..].to_i + 1 : 1
        kriteria_baru = "C#{number}"

        kriteria_model = CriteriaValue.new
        kriteria_model.kriteria = kriteria_baru
        kriteria_model.keterangan = params[:keterangan]
        kriteria_model.bobot_nilai = params[:bobot_nilai]

        if kriteria_model.save
            flash[:success] = "Criteria saved successfully."
            @save_time = Time.now
            redirect_to criteria_path(kriteria_model)
        else
            flash[:danger] = "Failed to save criteria."
            @save_time = Time.now
            redirect_to criteria_path(kriteria_model)
        end
        
    end

    def destroy
        kriteria_model = CriteriaValue.find(params[:deleteID])
        if kriteria_model.destroy
          flash[:success] = "Criteria deleted successfully."
          @save_time = Time.now
          redirect_to criteria_path(kriteria_model)
        else
          flash[:danger] = "Failed to delete criteria."
          @save_time = Time.now
          redirect_to criteria_path(kriteria_model)
        end
    end

    def edit
        @criteria = CriteriaValue.find(params[:id])
    end

    def update
        kriteria_model = CriteriaValue.find(params[:id])
       
        update_attributes = {
            keterangan: params[:keterangan],
            bobot_nilai: params[:bobot_nilai]
        }
        
        if kriteria_model.update(update_attributes)
          flash[:success] = "Criteria updated successfully."
          @save_time = Time.now
          redirect_to criteria_path(kriteria_model)
        else
          flash[:danger] = "Failed to update Criteria."
          @save_time = Time.now
          redirect_to criteria_path(kriteria_model)
        end
    end
end

app/helpers/criteria_helper.rb
module CriteriaHelper
end

app/views/criteria/edit.html.erb
<div class="layout-page">
  <div class="content-wrapper">
    <div class="row">
      <div class="col-md-6 mx-auto" style="margin-top: 50px">
        <div class="card mb-4">
          <h5 class="card-header">Criteria Edit Form</h5>
          <div class="card-body">
            <%= form_with model: @criteria, url: update_criteria_path(@criteria), method: :patch do |form| %>
           
            <div class="row g-2">
              <div class="col mb-0">
                <label for="emailWithTitle" class="form-label"
                  >Keterangan</label
                >
                <input
                  required
                  name="keterangan"
                  type="text"
                  id="emailWithTitle"
                  class="form-control"
                  placeholder="First Name"
                  value="<%= @criteria.keterangan %>"
                />
              </div>
              <div class="col mb-0">
                <label for="dobWithTitle" class="form-label">Bobot Nilai</label>
                <input
                  required
                  name="bobot_nilai"
                  type="text"
                  id="dobWithTitle"
                  class="form-control"
                  placeholder="Last Name"
                  value="<%= @criteria.bobot_nilai %>"
                />
              </div>
            </div>

            <%= form.submit "Update Data", class: "btn btn-primary", style: "margin-top:20px;" %>
           
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/criteria/index.html.erb
<!-- Layout container -->
<div class="layout-page">
  <!-- Content wrapper -->
  <div class="content-wrapper">
    <% if flash[:success] %>
    <div style="margin-top: 20px; position: fixed; top:20px; right:20px;" class="bs-toast toast fade show bg-success" role="alert" aria-live="assertive" aria-atomic="true">
      <div class="toast-header">
        <i class="bx bx-bell me-2"></i>
        <div class="me-auto fw-semibold">Message</div>
        <small><%= @save_time.nil? ? '' : "#{time_ago_in_words(@save_time)} ago" %></small>
        <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
      </div>
      <div class="toast-body">
        <%= flash[:success] %>
      </div>
    </div>
    <% end %>

    <% if flash[:danger] %>
    <div style="margin-top: 20px; position: fixed; top:20px; right:20px;" class="bs-toast toast fade show bg-danger" role="alert" aria-live="assertive" aria-atomic="true">
      <div class="toast-header">
        <i class="bx bx-bell me-2"></i>
        <div class="me-auto fw-semibold">Message</div>
        <small><%= @save_time.nil? ? '' : "#{time_ago_in_words(@save_time)} ago" %></small>
        <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
      </div>
      <div class="toast-body">
        <%= flash[:danger] %>
      </div>
    </div>
    <% end %>

    
    <!-- Content -->
    <div class="container-xxl flex-grow-1 container-p-y">
      <div class="card">
        <h5 class="card-header">Criteria data</h5>

        <div class="table-responsive text-nowrap">
          <table class="table table-hover">
            <thead>
              <tr>
                <th>No.</th>
                <th>Kriteria</th>
                <th>Keterangan</th>
                <th>Bobot Nilai</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody class="table-border-bottom-0">
              <% @kriteria.each_with_index do |krt, index| %>
                <tr>
                  <td><i class="fab fa-angular fa-lg text-danger me-3"></i>
                    <strong><%= index + 1 %></strong></td>
                  <td><%= krt.kriteria %></td>
                  <td>  <%= krt.keterangan %> 
                  <td>
                    <%= krt.bobot_nilai %>
                  </td>
                  
                  
                  <td>
                    <div class="dropdown">
                      <button
                        type="button"
                        class="btn p-0 dropdown-toggle hide-arrow"
                        data-bs-toggle="dropdown"
                      >
                        <i class="bx bx-dots-vertical-rounded"></i>
                      </button>
                      <div class="dropdown-menu">
                        <a href="/criteria/<%= krt.id %>/edit" class="dropdown-item"><i class="bx bx-edit-alt me-1"></i>
                          Edit</a>
                          
                        <a style="cursor:pointer;" class="dropdown-item" data-id="<%= krt.id %>" data-bs-toggle="modal" data-bs-target="#modalTopDelete"><i class="bx bx-trash me-1"></i>
                          Delete</a>
                      </div>
                    </div>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
    <!-- / Content --> <!-- FOOTER -->
    <%= render "partials/footer" %>
    <%= yield %>
    <!-- end footer -->
    <div class="content-backdrop fade"></div>
  </div>
  <!-- Content wrapper -->
</div>

<!-- / Layout page -->
<div class="buy-now">
  <a style="color:white;"
    target="_blank"
    class="btn btn-danger btn-buy-now"
    data-bs-toggle="modal"
    data-bs-target="#modalCenter"
  >
    <i class="menu-icon tf-icons bx bx-comment-add"></i>Add Data</a>
</div>

<%# ========== %>
 <!-- Modal Add Form-->
 <div class="modal fade" id="modalCenter" tabindex="-1" aria-hidden="true">
   <div class="modal-dialog modal-dialog-centered" role="document">
     <div class="modal-content">
       <div class="modal-header">
         <h5 class="modal-title" id="modalCenterTitle">Add Criteria Data</h5>
         <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
       </div>
       <div class="modal-body">
        <%= form_with url: '/criteria', method: :post do |form| %>
        <div class="row g-2">
          <div class="col mb-0">
            <label for="emailWithTitle" class="form-label">Keterangan</label>
            <input required name="keterangan" type="text" id="emailWithTitle" class="form-control" placeholder="Keterangan" />
          </div>
          <div class="col mb-0">
            <label for="dobWithTitle" class="form-label">Bobot Nilai</label>
            <input required name="bobot_nilai" type="text" id="dobWithTitle" class="form-control" placeholder="Bobot Nilai" />
          </div>
        </div>
       <div class="modal-footer">
         <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal"> Close </button>
         <%= form.submit "Save changes", class: "btn btn-primary" %>
       </div>
       <% end %>
     </div>
   </div>
 </div>
 </div>

 <!-- Modal hapus -->
<!-- Modal -->
<div class="modal fade" id="modalTopDelete" tabindex="-1">
  <div class="modal-dialog">
     <%= form_with url: '/criteria', class:'modal-content', method: :delete do |form| %>

      <div class="modal-header">
        <h5 class="modal-title" id="modalTopTitle">Delete Confirmation</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body"> Are you sure delete this data ? </div>
     
      <input type="text" name="deleteID" value="" id="deleteid" hidden>
      <div class="modal-footer">
        <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal"> Close </button>
        <%= form.submit "Delete", class: "btn btn-danger" %>
      </div>
      <% end %>
    
  </div>
</div>


<%= javascript_include_tag "form-criteria.js" %>