config/routes.rb
Rails.application.routes.draw do
  devise_for :users
 
 # get 'dashboards/index'
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  devise_scope :user do
    root to: 'devise/sessions#new'
  end

  get '/dashboard', to: 'dashboards#index'

  # Employee route
  get '/employee', to: 'employees#index'
  post '/employee', to: 'employees#create'
  delete '/employee', to: 'employees#destroy'
  get '/employee/:id/edit', to: 'employees#edit'
  patch '/employees/:id', to: 'employees#update', as: 'update_employee'

  # Criteria route
  get '/criteria', to: 'criteria#index'
  post '/criteria', to: 'criteria#create'
  delete '/criteria', to: 'criteria#destroy'
  get '/criteria/:id/edit', to: 'criteria#edit'
  patch '/criteria/:id', to: 'criteria#update', as: 'update_criteria'

  #Preference Value Route
  get '/preference', to: 'preference_value#index'
  post '/preference', to: 'preference_value#create'
  delete '/preference', to: 'preference_value#destroy'
  get '/preference/:id/edit', to: 'preference_value#edit'
  patch '/preference/:id', to: 'preference_value#update', as: 'update_preference'

  #create ranking
  get '/ranking', to: 'generate_ranking#index'
  post '/ranking', to: 'generate_ranking#create'
  get '/generate_rank/:id', to: 'generate_ranking#generate_rank'
  get '/ranking_data', to: 'generate_ranking#rank_all_data'
  get '/ranking/normalisasi', to: 'generate_ranking#normalisasi'
  get '/ranking/data/normalisasi', to: 'generate_ranking#normalisasiData'
  get '/ranking/data/bobot', to: 'generate_ranking#normalisasiBobot'
  get '/ranking/data/akhir', to: 'generate_ranking#hasilAkhir'
  get '/ranking/get_json', to: 'generate_ranking#get_json'
  
  get '/log/data_source', to: 'generate_ranking#log_data_source'
  get '/log/normalisasi', to: 'generate_ranking#log_normalisasi'
  get '/log/normalisasi_bobot', to: 'generate_ranking#log_normalisasi_bobot'
  get '/log/hasil_akhir', to: 'generate_ranking#log_hasil_akhir'
  
  # create report
  get 'generate_report/employee_report', to: 'generate_report#employee_report', as: 'generate_report_employee_report'

  get 'generate_report/hasil_report', to: 'generate_report#hasil_report'
  get 'generate_report/normalisasi_bobot', to: 'generate_report#normalisasi_bobot'
  get 'generate_report/normalisasi_report', to: 'generate_report#normalisasi_report'
  


end

app/models/employee.rb
class Employee < ApplicationRecord
    validates :first_name, presence: true
    validates :last_name, presence: true
    validates :date_of_birth, presence: true
    validates :gender, presence: true
    validates :address, presence: true
    validates :position, presence: true
    validates :department, presence: true
    validates :employment_status, presence: true
    validates :phone_number, presence: true
    validates :email, presence: true
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController

  def index
    # ambil semua data karyawan, dan tampilkan di views index
    @karyawan = Employee.all
    # respond_to do |format|
    #   format.html
    #   format.json { render json: EmployeeDatatable.new(params) }
    # end
  end

  def create
    employee = Employee.new
    employee.first_name = params[:first_name]
    employee.last_name = params[:last_name]
    employee.date_of_birth = params[:dob]
    employee.gender = params[:gender]
    employee.address = params[:address]
    employee.position = params[:position]
    employee.department = params[:department]
    employee.phone_number = params[:phone_num]
    employee.email = params[:email]
    employee.employment_status = params[:status]
    
    if employee.save
      flash[:success] = "Employee saved successfully."
      @save_time = Time.now
      redirect_to employee_path(employee)
    else
      flash[:danger] = "Failed to save employee."
      @save_time = Time.now
      redirect_to employee_path(employee)
    end
  end

  def destroy
    employee = Employee.find(params[:deleteID])
    if employee.destroy
      flash[:success] = "Employee deleted successfully."
      @save_time = Time.now
      redirect_to employee_path(employee)
    else
      flash[:danger] = "Failed to delete employee."
      @save_time = Time.now
      redirect_to employee_path(employee)
    end
  end

  def edit
    @karyawan = Employee.find(params[:id])
  end

  def update
    employee = Employee.find(params[:id])    
    update_attributes = {
        first_name: params[:first_name],
        last_name: params[:last_name],
        date_of_birth: params[:dob],
        gender: params[:gender],
        address: params[:address],
        position: params[:position],
        department: params[:department],
        email: params[:email],
        phone_number: params[:phone_num],
        employment_status: params[:status]
    }
    if employee.update(update_attributes)
      flash[:success] = "Employee updated successfully."
      @save_time = Time.now
      redirect_to employee_path(employee)
    else
      flash[:danger] = "Failed to update employee."
      @save_time = Time.now
      redirect_to employee_path(employee)
    end
  end    
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/edit.html.erb
<div class="layout-page">
  <div class="content-wrapper">
    <div class="row">
      <div class="col-md-6 mx-auto" style="margin-top: 50px">
        <div class="card mb-4">
          <h5 class="card-header">Employee Edit Form</h5>
          <div class="card-body">
            <%= form_with model: @karyawan, url: update_employee_path(@karyawan), method: :patch do |form| %>
           
            <div class="row g-2">
              <div class="col mb-0">
                <label for="emailWithTitle" class="form-label"
                  >First Name</label
                >
                <input
                  required
                  name="first_name"
                  type="text"
                  id="emailWithTitle"
                  class="form-control"
                  placeholder="First Name"
                  value="<%= @karyawan.first_name %>"
                />
              </div>
              <div class="col mb-0">
                <label for="dobWithTitle" class="form-label">Last Name</label>
                <input
                  required
                  name="last_name"
                  type="text"
                  id="dobWithTitle"
                  class="form-control"
                  placeholder="Last Name"
                  value="<%= @karyawan.last_name %>"
                />
              </div>
            </div>

            <div class="row g-2 mt-2">
              <div class="col mb-0">
                <label for="nameWithTitle" class="form-label"
                  >Date Of Birth</label
                >
                <input
                  required
                  name="dob"
                  type="text"
                  id="nameWithTitle"
                  class="form-control"
                  placeholder="DD / MM / YY"
                  value="<%= @karyawan.date_of_birth %>"
                />
              </div>
              <div class="col mb-0">
                <label for="exampleFormControlSelect1" class="form-label"
                  >Gender</label
                >
                <select
                  required
                  name="gender"
                  class="form-select"
                  id="exampleFormControlSelect1"
                  aria-label="Default select example"
                >
                  <option selected>Choose Gender</option>
                  <option value="Male" <%= 'selected' if @karyawan.gender == 'Male' %>>Male</option>
                  <option value="Female" <%= 'selected' if @karyawan.gender == 'Female' %>>Female</option>
                </select>
              </div>
            </div>

            <div class="row mt-2 g-2">
              <div class="col mb-3">
                <label for="exampleFormControlTextarea1" class="form-label"
                  >Address</label
                >
                <textarea
                  required
                  name="address"
                  class="form-control"
                  id="exampleFormControlTextarea1"
                  rows="3"
                ><%= @karyawan.address %></textarea>
              </div>
            </div>

            <div class="row g-2">
              <div class="col mb-0">
                <label for="nameWithTitle" class="form-label"
                  >Phone Number</label
                >
                <input
                  required
                  name="phone_num"
                  type="text"
                  id="nameWithTitle"
                  class="form-control"
                  placeholder="0819080xxxx"
                  value="<%= @karyawan.phone_number %>"
                />
              </div>
              <div class="col mb-0">
                <label for="nameWithTitle" class="form-label">Email</label>
                <input
                  required
                  name="email"
                  type="email"
                  id="nameWithTitle"
                  class="form-control"
                  placeholder="user@gmail.com"
                  value="<%= @karyawan.email %>"
                />
              </div>
            </div>

            <div class="row g-2 mt-2">
              <div class="col mb-0">
                <label for="nameWithTitle" class="form-label">Position</label>
                <select
                  required
                  name="position"
                  class="form-select"
                  id="exampleFormControlSelect1"
                  aria-label="Default select example"
                >
                  <option selected>Choose Position</option>
                  <option value="Ketua_Pengawas" <%= 'selected' if @karyawan.position == 'Ketua_Pengawas' %>>Ketua Pengawas</option>
                  <option value="Ketua_Koperasi" <%= 'selected' if @karyawan.position == 'Ketua_Koperasi' %>>Ketua Koperasi</option>
                  <option value="Sekretaris" <%= 'selected' if @karyawan.position == 'Sekretaris' %>>Sekretaris</option>
                  <option value="Bendahara" <%= 'selected' if @karyawan.position == 'Bendahara' %>>Bendahara</option>
                  <option value="Pengawas_I" <%= 'selected' if @karyawan.position == 'Pengawas_I' %>>Pengawas I</option>
                  <option value="Pengawas_II" <%= 'selected' if @karyawan.position == 'Pengawas_II' %>>Pengawas II</option>
                  <option value="Anggota" <%= 'selected' if @karyawan.position == 'Anggota' %>>Anggota</option>
                
                </select>
              </div>
              <div class="col mb-0">
                <label for="exampleFormControlSelect1" class="form-label"
                  >Departement</label
                >
                <select
                  required
                  name="department"
                  class="form-select"
                  id="exampleFormControlSelect1"
                  aria-label="Default select example"
                >
                  <option selected>Choose Departement</option>
                  <option value="Manajemen" <%= 'selected' if @karyawan.department == 'Manajemen' %>>Manajemen</option>
                  <option value="Pemasaran" <%= 'selected' if @karyawan.department == 'Pemasaran' %>>Pemasaran</option>
                  <option value="Keuangan" <%= 'selected' if @karyawan.department == 'Keuangan' %>>Keuangan</option>
                  <option value="Sumber Daya Manusia" <%= 'selected' if @karyawan.department == 'Sumber Daya Manusia' %>>Sumber Daya Manusia</option>
                  <option value="Operasional" <%= 'selected' if @karyawan.department == 'Operasional' %>>Operasional</option>
                  <option value="Layanan Anggota" <%= 'selected' if @karyawan.department == 'Layanan Anggota' %>>Layanan Anggota</option>
                  <option value="Teknologi Informasi" <%= 'selected' if @karyawan.department == 'Teknologi Informasi' %>>Teknologi Informasi</option>
                  <option value="Pertanian" <%= 'selected' if @karyawan.department == 'Pertanian' %>>Pertanian</option>
                  <option value="Proyek" <%= 'selected' if @karyawan.department == 'Proyek' %>>Proyek</option>
                  <option value="Ritel" <%= 'selected' if @karyawan.department == 'Ritel' %>>Ritel</option>
                </select>
              </div>
            </div>

            <div class="row mt-2 g-2">
              <div class="col mb-3">
                <label for="exampleFormControlSelect1" class="form-label"
                  >Status</label
                >
                <select
                  required
                  name="status"
                  class="form-select"
                  id="exampleFormControlSelect1"
                  aria-label="Default select example"
                >
                  <option selected>Choose Status</option>
                  <option value="Temporary" <%= 'selected' if @karyawan.employment_status == 'Temporary' %>>Temporary</option>
                  <option value="Internship" <%= 'selected' if @karyawan.employment_status == 'Internship' %>>Internship</option>
                  <option value="Full_Time" <%= 'selected' if @karyawan.employment_status == 'Full_Time' %>>Full Time</option>
                  <option value="Comission" <%= 'selected' if @karyawan.employment_status == 'Comission' %>>Comission</option>
                  <option value="Contract" <%= 'selected' if @karyawan.employment_status == 'Contract' %>>Contract</option>
                </select>
              </div>
            </div>
            <%= form.submit "Update Data", class: "btn btn-primary" %>
           
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/employees/index.html.erb
<!-- Layout container -->
<div class="layout-page">
  <!-- Content wrapper -->
  <div class="content-wrapper">
    <% if flash[:success] %>
    <div style="margin-top: 20px; position: fixed; top:20px; right:20px;" class="bs-toast toast fade show bg-success" role="alert" aria-live="assertive" aria-atomic="true">
      <div class="toast-header">
        <i class="bx bx-bell me-2"></i>
        <div class="me-auto fw-semibold">Message</div>
        <small><%= @save_time.nil? ? '' : "#{time_ago_in_words(@save_time)} ago" %></small>
        <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
      </div>
      <div class="toast-body">
        <%= flash[:success] %>
      </div>
    </div>
    <% end %>

    <% if flash[:danger] %>
    <div style="margin-top: 20px; position: fixed; top:20px; right:20px;" class="bs-toast toast fade show bg-danger" role="alert" aria-live="assertive" aria-atomic="true">
      <div class="toast-header">
        <i class="bx bx-bell me-2"></i>
        <div class="me-auto fw-semibold">Message</div>
        <small><%= @save_time.nil? ? '' : "#{time_ago_in_words(@save_time)} ago" %></small>
        <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
      </div>
      <div class="toast-body">
        <%= flash[:danger] %>
      </div>
    </div>
    <% end %>

    
    <!-- Content -->
    <div class="container-xxl flex-grow-1 container-p-y">
      <div class="card">
        <h5 class="card-header">Employee data</h5>
     <%= link_to 'Save as PDF', '/generate_report/employee_report', class: 'card-header',id: 'generate-pdf-link' %>
        <div class="table-responsive text-nowrap">
          <table class="table table-hover">
            <thead>
              <tr>
                <th>No.</th>
                <th>Full Name</th>
                <th>Position</th>
                <th>Departement</th>
                <th>Status</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody class="table-border-bottom-0">
              <% @karyawan.each_with_index do |kry, index| %>
                <tr>
                  <td><i class="fab fa-angular fa-lg text-danger me-3"></i>
                    <strong><%= index + 1 %></strong></td>
                  <td><%= kry.first_name %>
                    <%= kry.last_name %></td>
                  <td>
                    <%= kry.position.gsub('_', ' ') %>
                  </td>
                  <td>
                    <%= kry.department %>
                  </td>
                  <td>
                    <% if kry.employment_status == 'Temporary' %>
                      <span class="badge bg-label-primary me-1">
                        <%= kry.employment_status %></span>
                    <% end %>
                    <% if kry.employment_status == 'Internship' %>
                      <span class="badge bg-label-danger me-1">
                        <%= kry.employment_status %></span>
                    <% end %>
                    <% if kry.employment_status == 'Full-time' %>
                      <span class="badge bg-label-success me-1">
                        <%= kry.employment_status %></span>
                    <% end %>
                    <% if kry.employment_status == 'Commission' %>
                      <span class="badge bg-label-secondary me-1">
                        <%= kry.employment_status %></span>
                    <% end %>
                    <% if kry.employment_status == 'Contract' %>
                      <span class="badge bg-label-info me-1">
                        <%= kry.employment_status %></span>
                    <% end %>
                  </td>
                  <td>
                    <div class="dropdown">
                      <button
                        type="button"
                        class="btn p-0 dropdown-toggle hide-arrow"
                        data-bs-toggle="dropdown"
                      >
                        <i class="bx bx-dots-vertical-rounded"></i>
                      </button>
                      <div class="dropdown-menu">
                        <a href="/employee/<%= kry.id %>/edit" class="dropdown-item"><i class="bx bx-edit-alt me-1"></i>
                          Edit</a>
                          
                        <a style="cursor:pointer;" class="dropdown-item" data-id="<%= kry.id %>" data-bs-toggle="modal" data-bs-target="#modalTopDelete"><i class="bx bx-trash me-1"></i>
                          Delete</a>
                      </div>
                    </div>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
    <!-- / Content --> <!-- FOOTER -->
    <%= render "partials/footer" %>
    <%= yield %>
    <!-- end footer -->
    <div class="content-backdrop fade"></div>
  </div>
  <!-- Content wrapper -->
</div>

<!-- / Layout page -->
<div class="buy-now">
  <a style="color:white;"
    target="_blank"
    class="btn btn-danger btn-buy-now"
    data-bs-toggle="modal"
    data-bs-target="#modalCenter"
  >
    <i class="menu-icon tf-icons bx bx-comment-add"></i>Add Data</a>
</div>


<%# ========== %>

 <!-- Modal Add Form-->
 <div class="modal fade" id="modalCenter" tabindex="-1" aria-hidden="true">
   <div class="modal-dialog modal-dialog-centered" role="document">
     <div class="modal-content">
       <div class="modal-header">
         <h5 class="modal-title" id="modalCenterTitle">Add Employee Data</h5>
         <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
       </div>
       <div class="modal-body">
        <%= form_with url: '/employee', method: :post do |form| %>
        <div class="row g-2">
          <div class="col mb-0">
            <label for="emailWithTitle" class="form-label">First Name</label>
            <input required name="first_name" type="text" id="emailWithTitle" class="form-control" placeholder="First Name" />
          </div>
          <div class="col mb-0">
            <label for="dobWithTitle" class="form-label">Last Name</label>
            <input required name="last_name" type="text" id="dobWithTitle" class="form-control" placeholder="Last Name" />
          </div>
        </div>

         <div class="row g-2 mt-2">
           <div class="col mb-0">
             <label for="nameWithTitle" class="form-label">Date Of Birth</label>
             <input required name="dob" type="text" id="nameWithTitle" class="form-control" placeholder="DD / MM / YY" />
           </div>
           <div class="col mb-0">
            <label for="exampleFormControlSelect1" class="form-label">Gender</label>
            <select required name="gender" class="form-select" id="exampleFormControlSelect1" aria-label="Default select example">
              <option selected>Choose Gender</option>
              <option value="Male">Male</option>
              <option value="Female">Female</option>
            </select>
          </div>
         </div>

         <div class="row mt-2 g-2">
          <div class="col mb-3">
            <label for="exampleFormControlTextarea1" class="form-label">Address</label>
            <textarea required name="address" class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
          </div>
         </div>

         <div class="row g-2">
          <div class="col mb-0">
            <label for="nameWithTitle" class="form-label">Phone Number</label>
            <input required name="phone_num" type="text" id="nameWithTitle" class="form-control" placeholder="0819080xxxx" />
          </div>
          <div class="col mb-0">
            <label for="nameWithTitle" class="form-label">Email</label>
            <input required name="email" type="email" id="nameWithTitle" class="form-control" placeholder="user@gmail.com" />
         </div>
        </div>

        <div class="row g-2 mt-2">
          <div class="col mb-0">
            <label for="nameWithTitle" class="form-label">Position</label>
            <select required name="position" class="form-select" id="exampleFormControlSelect1" aria-label="Default select example">
              <option selected>Choose Position</option>
              <option value="Ketua_Pengawas">Ketua Pengawas</option>
              <option value="Ketua_Koperasi">Ketua Koperasi</option>
              <option value="Sekretaris">Sekretaris</option>
              <option value="Bendahara">Bendahara</option>
              <option value="Pengawas_I">Pengawas I</option>
              <option value="Pengawas_II">Pengawas II</option>
              <option value="Anggota">Anggota</option>
              
            </select>
          </div>
          <div class="col mb-0">
           <label for="exampleFormControlSelect1" class="form-label">Departement</label>
            <select required name="department" class="form-select" id="exampleFormControlSelect1" aria-label="Default select example">
             <option selected>Choose Departement</option>
             <option value="Manajemen">Manajemen</option>
             <option value="Pemasaran">Pemasaran</option>
             <option value="Keuangan">Keuangan</option>
             <option value="Sumber Daya Manusia">Sumber Daya Manusia</option>
             <option value="Operasional">Operasional</option>
             <option value="Layanan Anggota">Layanan Anggota</option>
             <option value="Teknologi Informasi">Teknologi Informasi</option>
             <option value="Pertanian">Pertanian</option>
             <option value="Proyek">Proyek</option>
             <option value="Ritel">Ritel</option>
            </select>
         </div>
        </div>

        <div class="row mt-2 g-2">
          <div class="col mb-3">
            <label for="exampleFormControlSelect1" class="form-label">Status</label>
            <select required name="status" class="form-select" id="exampleFormControlSelect1" aria-label="Default select example">
             <option selected>Choose Status</option>
             <option value="Temporary">Temporary</option>
             <option value="Internship">Internship</option>
             <option value="Full_Time">Full Time</option>
             <option value="Comission">Comission</option>
             <option value="Contract">Contract</option>
            </select>
          </div>
         </div>

       </div>
       <div class="modal-footer">
         <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal"> Close </button>
         <%= form.submit "Save changes", class: "btn btn-primary" %>
       </div>
       <% end %>
     </div>
   </div>
 </div>
<!-- Modal hapus -->
<!-- Modal -->
<div class="modal fade" id="modalTopDelete" tabindex="-1">
  <div class="modal-dialog">
     <%= form_with url: '/employee', class:'modal-content', method: :delete do |form| %>

      <div class="modal-header">
        <h5 class="modal-title" id="modalTopTitle">Delete Confirmation</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body"> Are you sure delete this data ? </div>
     
      <input type="text" name="deleteID" value="" id="deleteid" hidden>
      <div class="modal-footer">
        <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal"> Close </button>
        <%= form.submit "Delete", class: "btn btn-danger" %>
      </div>
      <% end %>
    
  </div>
</div>

<%= javascript_include_tag "form-employee.js" %>