config/routes.rb
Rails.application.routes.draw do
  devise_for :users
 
 # get 'dashboards/index'
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  devise_scope :user do
    root to: 'devise/sessions#new'
  end

  get '/dashboard', to: 'dashboards#index'

  # Employee route
  get '/employee', to: 'employees#index'
  post '/employee', to: 'employees#create'
  delete '/employee', to: 'employees#destroy'
  get '/employee/:id/edit', to: 'employees#edit'
  patch '/employees/:id', to: 'employees#update', as: 'update_employee'

  # Criteria route
  get '/criteria', to: 'criteria#index'
  post '/criteria', to: 'criteria#create'
  delete '/criteria', to: 'criteria#destroy'
  get '/criteria/:id/edit', to: 'criteria#edit'
  patch '/criteria/:id', to: 'criteria#update', as: 'update_criteria'

  #Preference Value Route
  get '/preference', to: 'preference_value#index'
  post '/preference', to: 'preference_value#create'
  delete '/preference', to: 'preference_value#destroy'
  get '/preference/:id/edit', to: 'preference_value#edit'
  patch '/preference/:id', to: 'preference_value#update', as: 'update_preference'

  #create ranking
  get '/ranking', to: 'generate_ranking#index'
  post '/ranking', to: 'generate_ranking#create'
  get '/generate_rank/:id', to: 'generate_ranking#generate_rank'
  get '/ranking_data', to: 'generate_ranking#rank_all_data'
  get '/ranking/normalisasi', to: 'generate_ranking#normalisasi'
  get '/ranking/data/normalisasi', to: 'generate_ranking#normalisasiData'
  get '/ranking/data/bobot', to: 'generate_ranking#normalisasiBobot'
  get '/ranking/data/akhir', to: 'generate_ranking#hasilAkhir'
  get '/ranking/get_json', to: 'generate_ranking#get_json'
  
  get '/log/data_source', to: 'generate_ranking#log_data_source'
  get '/log/normalisasi', to: 'generate_ranking#log_normalisasi'
  get '/log/normalisasi_bobot', to: 'generate_ranking#log_normalisasi_bobot'
  get '/log/hasil_akhir', to: 'generate_ranking#log_hasil_akhir'
  
  # create report
  get 'generate_report/employee_report', to: 'generate_report#employee_report', as: 'generate_report_employee_report'

  get 'generate_report/hasil_report', to: 'generate_report#hasil_report'
  get 'generate_report/normalisasi_bobot', to: 'generate_report#normalisasi_bobot'
  get 'generate_report/normalisasi_report', to: 'generate_report#normalisasi_report'
  


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/criteria_value.rb
class CriteriaValue < ApplicationRecord
    # Berfungsi untuk menyimpan informasi tentang bobot untuk setiap kriteria penilaian.
    # contoh : tanggung jawab => 3
    # field : 
    # id | kode_kriteria | kriteria | bobot

    validates :kriteria, presence:true
    validates :keterangan, presence: true
    validates :bobot_nilai, presence: true
end

app/models/data_source.rb
class DataSource < ApplicationRecord
end

app/models/employee.rb
class Employee < ApplicationRecord
    validates :first_name, presence: true
    validates :last_name, presence: true
    validates :date_of_birth, presence: true
    validates :gender, presence: true
    validates :address, presence: true
    validates :position, presence: true
    validates :department, presence: true
    validates :employment_status, presence: true
    validates :phone_number, presence: true
    validates :email, presence: true
end

app/models/hasil_akhir.rb
class HasilAkhir < ApplicationRecord
end

app/models/log_data_source.rb
class LogDataSource < ApplicationRecord
end

app/models/log_hasil.rb
class LogHasil < ApplicationRecord
end

app/models/log_normalisasi.rb
class LogNormalisasi < ApplicationRecord
end

app/models/log_normalisasi_bobot.rb
class LogNormalisasiBobot < ApplicationRecord
end

app/models/normalisasi.rb
class Normalisasi < ApplicationRecord
end

app/models/preference_value.rb
class PreferenceValue < ApplicationRecord
    # berfungsi sebagai data master preferensi penilaian 
    # contoh : Sangat baik => 4
    # field : 
    # id | keterangan | nilai
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/criteria_controller.rb
class CriteriaController < ApplicationController
    def index
        @kriteria = CriteriaValue.order(:id)    
        
    end

    def create
        latest_criteria = CriteriaValue.maximum(:kriteria)
        number = latest_criteria ? latest_criteria[1..].to_i + 1 : 1
        kriteria_baru = "C#{number}"

        kriteria_model = CriteriaValue.new
        kriteria_model.kriteria = kriteria_baru
        kriteria_model.keterangan = params[:keterangan]
        kriteria_model.bobot_nilai = params[:bobot_nilai]

        if kriteria_model.save
            flash[:success] = "Criteria saved successfully."
            @save_time = Time.now
            redirect_to criteria_path(kriteria_model)
        else
            flash[:danger] = "Failed to save criteria."
            @save_time = Time.now
            redirect_to criteria_path(kriteria_model)
        end
        
    end

    def destroy
        kriteria_model = CriteriaValue.find(params[:deleteID])
        if kriteria_model.destroy
          flash[:success] = "Criteria deleted successfully."
          @save_time = Time.now
          redirect_to criteria_path(kriteria_model)
        else
          flash[:danger] = "Failed to delete criteria."
          @save_time = Time.now
          redirect_to criteria_path(kriteria_model)
        end
    end

    def edit
        @criteria = CriteriaValue.find(params[:id])
    end

    def update
        kriteria_model = CriteriaValue.find(params[:id])
       
        update_attributes = {
            keterangan: params[:keterangan],
            bobot_nilai: params[:bobot_nilai]
        }
        
        if kriteria_model.update(update_attributes)
          flash[:success] = "Criteria updated successfully."
          @save_time = Time.now
          redirect_to criteria_path(kriteria_model)
        else
          flash[:danger] = "Failed to update Criteria."
          @save_time = Time.now
          redirect_to criteria_path(kriteria_model)
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def employeeName(id_emp)
        karyawan = Employee.find(id_emp)
        namaKaryawan = karyawan.first_name + " " + karyawan.last_name
        return namaKaryawan
    end
    def criteriaName(id_kriteria)
        kriteria = CriteriaValue.find(id_kriteria)
        namaKriteria = kriteria.keterangan
        return namaKriteria
    end
end

app/helpers/criteria_helper.rb
module CriteriaHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/generate_ranking_helper.rb
module GenerateRankingHelper
    
end

app/helpers/generate_report_helper.rb
module GenerateReportHelper
end

app/helpers/preference_value_helper.rb
module PreferenceValueHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AplikasiSpk</title>
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <%= csrf_meta_tags %> 
    <%= csp_meta_tag %> <%# file css %> 
    <%= stylesheet_link_tag "application", 'data-turbolinks-track': 'reload' %> 
    <%= stylesheet_link_tag "core", 'data-turbolinks-track': 'reload' %> 
    <%= stylesheet_link_tag "theme-default", 'data-turbolinks-track': 'reload' %> 
    <%= stylesheet_link_tag "demo", 'data-turbolinks-track': 'reload'%> 
    <%= stylesheet_link_tag "boxicons", 'data-turbolinks-track': 'reload'%>
    <%= stylesheet_link_tag "perfect-scrollbar", 'data-turbolinks-track': 'reload'%>
    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Public+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/chart.js@2.9.1/dist/Chart.min.css">
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.1/dist/Chart.min.js"></script>
     <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.4.0/jspdf.umd.min.js"></script>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "helpers.js" %> 
    <%= javascript_include_tag "config.js" %> 
  </head>

  <body>
  <div class="layout-wrapper layout-content-navbar">
      <div class="layout-container">
        <%= render 'partials/sidebar' %> <%= yield %>
      </div>
    </div>
  </body>
  <%= javascript_include_tag "jquery.js" %> 
  <%= javascript_include_tag "popper.js" %> 
  <%= javascript_include_tag "bootstrap.js" %> 
  <%= javascript_include_tag "menu.js" %> 
  <%= javascript_include_tag "main.js" %>
  <%= javascript_include_tag "perfect-scrollbar.js" %>
  <%= javascript_include_tag "chart_ranking.js"%>   
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Devise Layout</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

</head>
<body>
<div class="container">
  <%= yield %>
</div>
</body>
</html>

app/views/partials/_footer.html.erb
    <!-- Footer -->
    <footer class="content-footer footer bg-footer-theme">
      <div
        class="container-xxl d-flex flex-wrap justify-content-between py-2 flex-md-row flex-column"
      >
        <div class="mb-2 mb-md-0">
          ©
          <script>
            document.write(new Date().getFullYear());
          </script>
          , made with ❤️ by Septian
       
        </div>
      </div>
    </footer>
    <!-- / Footer -->

app/views/partials/_sidebar.html.erb
<!-- Menu -->
<aside id="layout-menu" class="layout-menu menu-vertical menu bg-menu-theme">
  <div class="app-brand demo">
    <a href="/" class="app-brand-link">
      <img src="<%= asset_path('avatars/logo_koperasi.png') %>" alt="Logo Koperasi" width="50" height="50">
  
      <span class="demo menu-text fw-bolder ms-2">Koperasi Hiswana Migas</span>
    </a>

    <a
      href="javascript:void(0);"
      class="layout-menu-toggle menu-link text-large ms-auto d-block d-xl-none"
    >
      <i class="bx bx-chevron-left bx-sm align-middle"></i>
    </a>
  </div>

  <div class="menu-inner-shadow"></div>

  <ul class="menu-inner py-1">
    <!-- Dashboard -->
    <li class="menu-item active">
      <%= link_to root_path, class: 'menu-link' do %>
        <i class="menu-icon tf-icons bx bx-home-circle"></i>
        <div data-i18n="Analytics">Dashboard</div>
      <% end %>

    </li>

    <li class="menu-header small text-uppercase">
      <span class="menu-header-text">Master</span>
    </li>
    <li class="menu-item">
      <%= link_to employee_path, class: "menu-link" do %>
        <i class="menu-icon tf-icons bx bx-dock-top"></i>
        <div data-i18n="Account Settings">Employee Data</div>
      <% end %>

    </li>
    <li class="menu-item">
      <%= link_to criteria_path, class: "menu-link" do %>
        <i class="menu-icon tf-icons bx bx-dock-top"></i>
        <div data-i18n="Account Settings">Criteria Data</div>
      <% end %>

    </li>
    <li class="menu-item">
      <%= link_to preference_path, class: "menu-link" do %>
        <i class="menu-icon tf-icons bx bx-dock-top"></i>
        <div data-i18n="Account Settings">Preference Data</div>
      <% end %>

    </li>
    <!-- Components -->
    <li class="menu-header small text-uppercase"><span class="menu-header-text">Generate Ranking</span></li>
    <!-- Cards -->
    <li class="menu-item">
      <%= link_to '/ranking', class: "menu-link" do %>
        <i class="menu-icon tf-icons bx bx-collection"></i>
        <div data-i18n="Basic">Create Data</div>
      <% end %>
    </li>
    <li class="menu-item">
      <%= link_to '/ranking_data', class: "menu-link" do %>
        <i class="menu-icon tf-icons bx bx-collection"></i>
        <div data-i18n="Basic">Data Source</div>
      <% end %>
    </li>
    <li class="menu-item">
      <%= link_to '/ranking/data/normalisasi', class: "menu-link" do %>
        <i class="menu-icon tf-icons bx bx-collection"></i>
        <div data-i18n="Basic">Normalisasi Data</div>
      <% end %>
    </li>
    <li class="menu-item">
      <%= link_to '/ranking/data/bobot', class: "menu-link" do %>
        <i class="menu-icon tf-icons bx bx-collection"></i>
        <div data-i18n="Basic">Normalisasi Bobot</div>
      <% end %>
    </li>
    <li class="menu-item">
      <%= link_to '/ranking/data/akhir', class: "menu-link" do %>
        <i class="menu-icon tf-icons bx bx-collection"></i>
        <div data-i18n="Basic">Hasil Akhir</div>
      <% end %>
    </li>

    <li class="menu-item">
      <%= button_to  destroy_user_session_path, method: :delete, class: "menu-link" do %>
        <i class="menu-icon tf-icons bx bx-collection"></i>
        <div data-i18n="Basic">Logout</div>
      <% end %>
    </li>


  </ul>
</aside>
<!-- / Menu -->